#!/usr/bin/env python3
"""Generate data/models.json (canonical registry) — edit THIS file, then run:
    python3 scripts/generate_registry.py
to regenerate data/models.csv.
"""
import json, os

R = os.path.join(os.path.dirname(__file__), "..")

# category: llm | reasoning | coding | vlm | image | video | music | tts | asr | embedding | reranker | model3d
M = [
 # ---- Frontier LLMs ----
 dict(id="deepseek-v4-pro-0813", name="DeepSeek V4-Pro-0813", org="DeepSeek", category="llm",
      params_total="1.6T", params_active="49B", architecture="MoE", context="1M",
      modality="text", license="MIT", release="2026-08-13",
      hf="deepseek-ai/DeepSeek-V4-Pro-0813", github="https://github.com/deepseek-ai",
      api="https://platform.deepseek.com", notes="GA build; open weights; reasoning efforts; 384K max output", commercial=True),
 dict(id="qwen3.8-2.4t-a95b", name="Qwen3.8-2.4T-A95B", org="Qwen (Alibaba)", category="llm",
      params_total="2.4T", params_active="95B", architecture="MoE (512 experts, hybrid Gated-DeltaNet attention)", context="262K-1M",
      modality="text", license="Qwen3.8-Max license (custom)", release="2026-08-12",
      hf="Qwen/Qwen3.8-2.4T-A95B", github="https://github.com/QwenLM", api="https://www.alibabacloud.com/product/bailian",
      notes="Open twin of Qwen3.8-Max; ~400GB at 1-bit; 27B sibling is Apache 2.0", commercial=True),
 dict(id="kimi-k2.6", name="Kimi K2.6", org="Moonshot AI", category="llm",
      params_total="1T", params_active="32B", architecture="MoE (agent-swarm lineage)", context="262K",
      modality="text+image+video", license="Modified MIT", release="2026-04-20",
      hf="moonshotai/Kimi-K2.6", github="https://github.com/MoonshotAI/Kimi-K2", api="https://platform.moonshot.ai",
      notes="Long-horizon agents; ties GPT-5.5-class on SWE-bench Pro (v.r.)", commercial=True),
 dict(id="glm-5.2", name="GLM-5.2", org="Z.ai (Zhipu)", category="llm",
      params_total="744B", params_active=None, architecture="MoE", context="1M",
      modality="text", license="MIT", release="2026-06-13",
      hf="zai-org/GLM-5.2", github="https://github.com/zai-org/GLM-5", api="https://z.ai",
      notes="Open weights BF16+FP8; agentic coding; GLM Coding Plan", commercial=True),
 dict(id="qwen3.5", name="Qwen3.5-397B-A17B", org="Qwen (Alibaba)", category="llm",
      params_total="397B", params_active="17B", architecture="MoE", context="1M",
      modality="text+image+video", license="Apache 2.0", release="2026-02-16",
      hf="Qwen/Qwen3.5-397B-A17B", github="https://github.com/QwenLM/Qwen3", api="https://www.alibabacloud.com/product/bailian",
      notes="Agentic flagship; native image+video input; computer-use agents", commercial=True),
 dict(id="qwen3.6", name="Qwen3.6-35B-A3B", org="Qwen (Alibaba)", category="llm",
      params_total="35B", params_active="3B", architecture="MoE", context="256K",
      modality="text+image+video", license="Apache 2.0", release="2026-04-15",
      hf="Qwen/Qwen3.6-35B-A3B", github="https://github.com/QwenLM", api="https://www.alibabacloud.com/product/bailian",
      notes="Small flagship; image/video input; huge GGUF ecosystem", commercial=True),
 dict(id="qwen3-235b-a22b", name="Qwen3-235B-A22B", org="Qwen (Alibaba)", category="llm",
      params_total="235B", params_active="22B", architecture="MoE", context="256K",
      modality="text", license="Apache 2.0", release="2025-07",
      hf="Qwen/Qwen3-235B-A22B-Instruct", github="https://github.com/QwenLM/Qwen3", ollama="qwen3:235b",
      notes="Best-documented self-host MoE; thinking mode", commercial=True),
 dict(id="mistral-large-3", name="Mistral Large 3", org="Mistral AI", category="llm",
      params_total="675B", params_active="41B", architecture="MoE (2.5B vision encoder incl.)", context="256K",
      modality="text+image", license="Apache 2.0", release="2025-12-02",
      hf="mistralai/Mistral-Large-3-675B-Instruct-2512-BF16", github="https://github.com/mistralai", api="https://mistral.ai",
      notes="Largest open MoE from a Western lab; 40-100+ languages", commercial=True),
 dict(id="llama-4-maverick", name="Llama 4 Maverick", org="Meta", category="llm",
      params_total="402B", params_active="17B", architecture="MoE (128 experts)", context="1M",
      modality="text+image in", license="Llama 4 Community (700M MAU cap)", release="2025-04",
      hf="meta-llama/Llama-4-Maverick-17B-128E-Instruct", github="https://github.com/meta-llama/llama-models",
      notes="Native tool use; fine-tunes restricted >700M MAU", commercial=True),
 dict(id="llama-4-scout", name="Llama 4 Scout", org="Meta", category="llm",
      params_total="109B", params_active="17B", architecture="MoE (16 experts)", context="10M",
      modality="text+image in", license="Llama 4 Community", release="2025-04",
      hf="meta-llama/Llama-4-Scout-17B-16E-Instruct", github="https://github.com/meta-llama/llama-models",
      notes="Longest context of any model; single 80GB GPU at Q4", commercial=True),
 dict(id="deepseek-v3.2", name="DeepSeek V3.2 / V3.2-Speciale", org="DeepSeek", category="llm",
      params_total="685B", params_active="37B", architecture="MoE", context="128K",
      modality="text", license="MIT", release="2025-09",
      hf="deepseek-ai/DeepSeek-V3.2", github="https://github.com/deepseek-ai", api="https://platform.deepseek.com",
      notes="Proven workhorse; huge ecosystem", commercial=True),
 dict(id="deepseek-v4-flash", name="DeepSeek V4-Flash-0731", org="DeepSeek", category="llm",
      params_total=None, params_active=None, architecture="MoE", context="128K+",
      modality="text", license="MIT", release="2026-07-31",
      hf="deepseek-ai/DeepSeek-V4-Flash", github="https://github.com/deepseek-ai", api="https://platform.deepseek.com",
      ollama="deepseek-v4-flash", notes="Cheap fast tier; open weights 166.9GB (48 shards)", commercial=True),
 dict(id="gemma-4-31b", name="Gemma 4 31B", org="Google DeepMind", category="llm",
      params_total="31B", params_active=None, architecture="Dense", context="128K+",
      modality="text+image (+audio in edge variants)", license="Apache 2.0", release="2026-04-02",
      hf="google/gemma-4-31B-it", github="https://github.com/google-gemma", ollama="google/gemma-4-31b-it",
      notes="Frontier-dense on one GPU (~18-22GB Q4); token-efficient (v.r.)", commercial=True),
 dict(id="gemma-4-26b-a4b", name="Gemma 4 26B-A4B", org="Google DeepMind", category="llm",
      params_total="26B", params_active="4B", architecture="MoE", context="128K+",
      modality="text+image", license="Apache 2.0", release="2026-04-02",
      hf=None, ollama="google/gemma-4-26b-it", notes="MoE efficiency tier", commercial=True),
 dict(id="gemma-4-e4b", name="Gemma 4 E4B / E2B", org="Google DeepMind", category="llm",
      params_total="5-8B", params_active=None, architecture="Dense (edge)", context="128K",
      modality="text+image+audio", license="Apache 2.0", release="2026-04-02",
      hf=None, ollama="gemma4:e4b", notes="Phone/laptop; E4B ~3GB", commercial=True),
 dict(id="gpt-oss-120b", name="gpt-oss-120b", org="OpenAI", category="reasoning",
      params_total="117B", params_active="5.1B", architecture="MoE (36 layers, MXFP4)", context="131K",
      modality="text", license="Apache 2.0", release="2025-08",
      hf="openai/gpt-oss-120b", github="https://github.com/openai/openai-open-models", api=None,
      ollama="gpt-oss:120b", notes="Not on OpenAI API; fits single 80GB GPU", commercial=True),
 dict(id="gpt-oss-20b", name="gpt-oss-20b", org="OpenAI", category="reasoning",
      params_total="21B", params_active="3.6B", architecture="MoE (MXFP4)", context="131K",
      modality="text", license="Apache 2.0", release="2025-08",
      hf="openai/gpt-oss-20b", ollama="gpt-oss:20b", notes="Laptop reasoning pick (~16GB)", commercial=True),
 dict(id="glm-4.7", name="GLM-4.7", org="Z.ai (Zhipu)", category="coding",
      params_total="355B", params_active="32B", architecture="MoE", context="128K+",
      modality="text", license="MIT", release="2025-10",
      hf="zai-org/GLM-4.7", github="https://github.com/zai-org/GLM-4.7", api="https://z.ai",
      ollama="glm-4.7", notes="Production agentic workhorse", commercial=True),
 dict(id="qwen3-coder-next", name="Qwen3-Coder-Next", org="Qwen (Alibaba)", category="coding",
      params_total=None, params_active=None, architecture="MoE", context="256K",
      modality="text", license="Apache 2.0", release="2026-02-03",
      hf="Qwen", github="https://github.com/QwenLM", notes="IDE-grade tool use", commercial=True),
 dict(id="qwen3-coder-30b", name="Qwen3-Coder-30B", org="Qwen (Alibaba)", category="coding",
      params_total="30B", params_active="3B", architecture="MoE", context="128K",
      modality="text", license="Apache 2.0", release="2025-07",
      hf="Qwen/Qwen3-Coder-30B-A3B-Instruct", ollama="qwen3-coder:30b", notes="Best open 30B coder", commercial=True),
 dict(id="devstral-small-2", name="Devstral Small 2", org="Mistral AI", category="coding",
      params_total="24B", params_active=None, architecture="Dense", context="128K",
      modality="text", license="Apache 2.0", release="2026",
      hf="mistralai", ollama="devstral:24b", notes="Open SWE-agent default", commercial=True),
 dict(id="minimax-m2.5", name="MiniMax M2.5", org="MiniMax", category="llm",
      params_total="~200B", params_active=None, architecture="MoE", context="~200K",
      modality="text", license="MiniMax community (custom LICENSE-MODEL)", release="2026-02-12",
      hf="MiniMaxAI/MiniMax-M2.5", api="https://www.minimax.io", notes="SWE-bench ~80 (v.r.); FP8; NVIDIA NVFP4 quant available", commercial=True),
 dict(id="mimo-v2-flash", name="MiMo-V2-Flash", org="Xiaomi", category="llm",
      params_total=None, params_active=None, architecture="MoE", context="256K",
      modality="text", license="MIT", release="2025-12",
      hf="XiaomiMiMo/MiMo-V2-Flash", notes="Surprise efficiency leader", commercial=True),
 dict(id="sarvam-105b", name="Sarvam 105B", org="Sarvam AI", category="llm",
      params_total="105B", params_active=None, architecture="MoE", context="128K",
      modality="text", license="Sarvam license", release="2026",
      hf="sarvamai", notes="Indic-language frontier (22 languages)", commercial=True),
 dict(id="qwen3-8b", name="Qwen3-8B", org="Qwen (Alibaba)", category="llm",
      params_total="8B", params_active=None, architecture="Dense", context="128K",
      modality="text", license="Apache 2.0", release="2025-04",
      hf="Qwen/Qwen3-8B", ollama="qwen3:8b", notes="The default free local LLM; 201 languages", commercial=True),
 dict(id="qwen3.8-27b", name="Qwen3.8-27B", org="Qwen (Alibaba)", category="llm",
      params_total="27B", params_active=None, architecture="Dense", context="262K+",
      modality="text", license="Apache 2.0", release="2026-08-03",
      hf="Qwen/Qwen3.8-27B", ollama="qwen3.8:27b", notes="Flagship-per-GPU; Apache 2.0", commercial=True),
 dict(id="phi-4-mini", name="Phi-4-mini", org="Microsoft", category="llm",
      params_total="3.8B", params_active=None, architecture="Dense", context="128K",
      modality="text", license="MIT", release="2025-02",
      hf="microsoft/Phi-4-mini-instruct", ollama="phi4-mini", notes="CPU-friendly edge default", commercial=True),
 dict(id="phi-4-reasoning", name="Phi-4-Reasoning", org="Microsoft", category="reasoning",
      params_total="14B", params_active=None, architecture="Dense", context="128K",
      modality="text", license="MIT", release="2025-04",
      hf="microsoft/Phi-4-reasoning-plus", notes="Edge reasoning research", commercial=True),
 dict(id="deepseek-r1", name="DeepSeek-R1", org="DeepSeek", category="reasoning",
      params_total="671B", params_active="37B", architecture="MoE (CoT RL)", context="128K",
      modality="text", license="MIT", release="2025-01",
      hf="deepseek-ai/DeepSeek-R1", ollama="deepseek-r1:671b", notes="The open reasoning legend", commercial=True),
 dict(id="deepseek-r1-distill-14b", name="DeepSeek-R1-Distill-14B", org="DeepSeek", category="reasoning",
      params_total="14B", params_active=None, architecture="Dense (distill)", context="128K",
      modality="text", license="MIT", release="2025-01",
      hf="deepseek-ai/DeepSeek-R1-Distill-Qwen-14B", ollama="deepseek-r1:14b", notes="Laptop reasoning ~9GB", commercial=True),
 dict(id="magistral-small", name="Magistral Small", org="Mistral AI", category="reasoning",
      params_total="~30B", params_active=None, architecture="Dense", context="128K",
      modality="text", license="Apache 2.0", release="2026",
      hf="mistralai", notes="Self-hosted reasoning, EU", commercial=True),
 dict(id="minimax-m2.5-vlm", name="MiniMax M2 (VLM)", org="MiniMax", category="vlm",
      params_total="~200B", params_active=None, architecture="MoE", context="~200K",
      modality="text+image", license="Apache 2.0", release="2025",
      hf="MiniMaxAI/MiniMax-M2", notes="Multimodal agentic model", commercial=True),
 dict(id="ui-tars", name="UI-TARS", org="ByteDance", category="vlm",
      params_total=None, params_active=None, architecture=None, context=None,
      modality="GUI agent", license="Apache 2.0 (check weights)", release="2025",
      hf=None, github="https://github.com/bytedance/UI-TARS", notes="GUI computer-use model", commercial=True),
 dict(id="qwen3-vl", name="Qwen3-VL", org="Qwen (Alibaba)", category="vlm",
      params_total="8-72B", params_active=None, architecture="VLM", context="128K+",
      modality="text+image+video", license="Apache 2.0", release="2025",
      hf="Qwen", notes="Doc/UI vision champion lineage", commercial=True),
 dict(id="qwen2.5-vl", name="Qwen2.5-VL", org="Qwen (Alibaba)", category="vlm",
      params_total="3-72B", params_active=None, architecture="VLM", context="128K",
      modality="text+image+video", license="Apache 2.0", release="2025",
      hf="Qwen/Qwen2.5-VL-72B-Instruct", notes="Document/UI vision classic", commercial=True),
 # ---- Image ----
 dict(id="qwen-image-2512", name="Qwen-Image-2512", org="Qwen (Alibaba)", category="image",
      params_total="20B+", params_active=None, architecture="DiT+LLM", context=None,
      modality="image", license="Apache 2.0", release="2025-12",
      hf="Qwen/Qwen-Image-2512", github="https://github.com/QwenLM/Qwen-Image", notes="Open #1 (10k+ blind rounds, v.r.); multilingual text incl. Arabic RTL", commercial=True),
 dict(id="flux-2-dev", name="FLUX.2 [dev]", org="Black Forest Labs", category="image",
      params_total="32B", params_active=None, architecture="DiT", context=None,
      modality="image", license="FLUX.2 [dev] Non-Commercial", release="2025-11",
      hf="black-forest-labs/FLUX.2-dev", api="https://bfl.ai", notes="Photorealism king; commercial >$100k revenue needs license", commercial=False),
 dict(id="flux-2-klein", name="FLUX.2 [klein]", org="Black Forest Labs", category="image",
      params_total="4B/9B", params_active=None, architecture="Distilled DiT", context=None,
      modality="image", license="FLUX.2 [dev]-style", release="2025-11",
      hf="black-forest-labs/FLUX.2-klein", notes="Real-time/edge; ~13GB", commercial=True),
 dict(id="z-image-turbo", name="Z-Image-Turbo", org="Z.ai (Zhipu)", category="image",
      params_total="6B", params_active=None, architecture="Distilled diffusion", context=None,
      modality="image", license="Apache 2.0", release="2025",
      hf="zai-org/Z-Image-Turbo", notes="Throughput-per-dollar; bilingual text", commercial=True),
 dict(id="glm-image", name="GLM-Image", org="Z.ai (Zhipu)", category="image",
      params_total="9B+7B", params_active=None, architecture="AR + DiT hybrid", context=None,
      modality="image", license="MIT", release="2025",
      hf="zai-org/GLM-Image", notes="Best typography/posters", commercial=True),
 dict(id="sd-3.5-large", name="Stable Diffusion 3.5 Large", org="Stability AI", category="image",
      params_total="8B", params_active=None, architecture="MMDiT", context=None,
      modality="image", license="Stability Community", release="2024-10",
      hf="stabilityai/stable-diffusion-3.5-large", notes="The LoRA ecosystem king", commercial=True),
 dict(id="hunyuanimage-3", name="HunyuanImage 3.0", org="Tencent", category="image",
      params_total="80B", params_active="13B", architecture="Multimodal AR MoE", context=None,
      modality="image", license="Tencent Hunyuan Community", release="2026",
      hf="Tencent-Hunyuan/HunyuanImage-3.0", notes="Long complex prompts; 40GB+", commercial=True),
 # ---- Video ----
 dict(id="wan-2.2", name="Wan 2.2 / 2.5", org="Wan (Alibaba)", category="video",
      params_total="1.3B-14B", params_active=None, architecture="DiT", context=None,
      modality="video (+audio in 2.5)", license="Apache 2.0", release="2025",
      hf="Wan-AI/Wan2.2-T2V-A14B", github="https://github.com/Wan-Video/Wan2.2", notes="Cleanest commercial license", commercial=True),
 dict(id="ltx-2.5", name="LTX-2.5", org="Lightricks", category="video",
      params_total="22B", params_active=None, architecture="Video DiT", context=None,
      modality="video+audio", license="LTX Community (<$10M ARR)", release="2026",
      hf="Lightricks/LTX-2.5", notes="4K/20s local + native audio", commercial=True),
 dict(id="minimax-h3", name="MiniMax H3 (Hailuo 3.0)", org="MiniMax", category="video",
      params_total="33.1B", params_active=None, architecture=None, context=None,
      modality="video+audio", license="MiniMax Community (<$20M rev)", release="2026",
      hf="MiniMaxAI/MiniMax-H3", api="https://www.minimax.io", notes="Reference-heavy scenes; stereo audio", commercial=True),
 dict(id="hunyuanvideo-1.5", name="HunyuanVideo 1.5", org="Tencent", category="video",
      params_total="13B", params_active=None, architecture="MMDiT", context=None,
      modality="video+audio", license="Tencent Hunyuan Community (100M MAU)", release="2025",
      hf="Tencent-Hunyuan/HunyuanVideo-1.5", notes="Cinematic 720p/15s; modest hardware", commercial=True),
 dict(id="cogvideox", name="CogVideoX 1.5", org="Zhipu", category="video",
      params_total="5B", params_active=None, architecture=None, context=None,
      modality="video", license="CogVideoX License", release="2024-08",
      hf="THUDM/CogVideoX-5b", notes="Open video pioneer", commercial=True),
 dict(id="mochi-1", name="Mochi-1", org="Genmo", category="video",
      params_total="10B", params_active=None, architecture="MMDiT", context=None,
      modality="video", license="Apache 2.0", release="2024-10",
      hf="genmo/mochi-1-preview", notes="Open baseline research", commercial=True),
 dict(id="open-sora-2", name="Open-Sora 2.0", org="HPC-AI", category="video",
      params_total=None, params_active=None, architecture=None, context=None,
      modality="video", license="MIT (code; check weights)", release="2025",
      hf="hpcaitech/Open-Sora", notes="Fully-open pipeline ambitions", commercial=True),
 # ---- Audio / music ----
 dict(id="ace-step-1.5", name="ACE-Step 1.5", org="ACE / FunAudio", category="music",
      params_total=None, params_active=None, architecture="Hybrid LM", context=None,
      modality="music", license="open weights (check)", release="2026-01",
      github="https://github.com/ace-step/ACE-Step", notes="Text→songs 50+ langs, covers, 10-min, consumer GPUs", commercial=True),
 dict(id="musicgen", name="MusicGen", org="Meta", category="music",
      params_total="1.5B", params_active=None, architecture="EnCodec+Transformer", context=None,
      modality="music", license="MIT code / CC-BY-NC weights", release="2023",
      github="https://github.com/facebookresearch/audiocraft", notes="Classic baseline", commercial=False),
 dict(id="stable-audio-open", name="Stable Audio Open", org="Stability AI", category="music",
      params_total=None, params_active=None, architecture=None, context=None,
      modality="audio (SFX/stems)", license="Stability Community", release="2024",
      hf="stabilityai/stable-audio-open-1.0", notes="Text→SFX/music", commercial=True),
 # ---- TTS ----
 dict(id="kokoro", name="Kokoro-82M", org="Hexgrad", category="tts",
      params_total="82M", params_active=None, architecture=None, context=None,
      modality="speech", license="Apache 2.0", release="2025",
      hf="hexgrad/Kokoro-82M", ollama="kokoro", notes="CPU real-time; ~200x RT on GPU; 54 presets", commercial=True),
 dict(id="qwen3-tts", name="Qwen3-TTS", org="Qwen (Alibaba)", category="tts",
      params_total="0.6B-1.7B", params_active=None, architecture=None, context=None,
      modality="speech", license="Apache 2.0", release="2026-01",
      hf="Qwen/Qwen3-TTS-12Hz-1.7B-CustomVoice", notes="3-second cloning, 10 langs, NL emotion control, 97ms streaming", commercial=True),
 dict(id="chatterbox", name="Chatterbox (Turraa)", org="Resemble AI", category="tts",
      params_total="0.35B-1.2B", params_active=None, architecture=None, context=None,
      modality="speech", license="MIT", release="2025",
      hf="ResembleAI/chatterbox", notes="5-10s cloning, 23 langs (multilingual variant)", commercial=True),
 dict(id="cosyvoice-3", name="CosyVoice 3.0", org="FunAudioLLM", category="tts",
      params_total="0.5B", params_active=None, architecture=None, context=None,
      modality="speech", license="Apache 2.0", release="2025",
      github="https://github.com/FunAudioLLM/CosyVoice", notes="Zero-shot clone, 150ms streaming", commercial=True),
 dict(id="f5-tts", name="F5-TTS", org="community", category="tts",
      params_total="0.3B", params_active=None, architecture="Flow matching", context=None,
      modality="speech", license="MIT", release="2024-10",
      github="https://github.com/SWivid/F5-TTS", notes="Fast cloning (33x Fast)", commercial=True),
 dict(id="piper", name="Piper", org="Rhasspy", category="tts",
      params_total="tiny", params_active=None, architecture=None, context=None,
      modality="speech", license="MIT", release="2023",
      github="https://github.com/rhasspy/piper", notes="Edge TTS for RPi/IoT", commercial=True),
 dict(id="vibevoice", name="VibeVoice", org="Microsoft", category="tts",
      params_total="3B-7B", params_active=None, architecture=None, context=None,
      modality="speech (long-form podcast)", license="MIT (research terms)", release="2026",
      hf="microsoft/VibeVoice", notes="Multi-speaker long-form", commercial=False),
 # ---- ASR ----
 dict(id="whisper-large-v3", name="Whisper large-v3 / turbo", org="OpenAI", category="asr",
      params_total="1.55B / 0.8B", params_active=None, architecture="Encoder-decoder transformer", context=None,
      modality="speech→text", license="MIT", release="2024-11",
      hf="openai/whisper-large-v3-turbo", notes="99 langs; the reference (faster-whisper, whisper.cpp, WhisperX)", commercial=True),
 dict(id="qwen3-asr", name="Qwen3-ASR", org="Qwen (Alibaba)", category="asr",
      params_total="0.6B/1.7B", params_active=None, architecture=None, context=None,
      modality="speech→text", license="Apache 2.0", release="2026",
      hf="Qwen/Qwen3-ASR", notes="52 langs; strong Mandarin/Asian", commercial=True),
 dict(id="parakeet-tdt", name="Parakeet TDT 0.6B", org="NVIDIA", category="asr",
      params_total="~600M", params_active=None, architecture=None, context=None,
      modality="speech→text", license="Apache 2.0", release="2024-10",
      hf="nvidia/parakeet-tdt-0.6b-v3", notes="Fastest batch EN; ~1.4% WER (v.r.)", commercial=True),
 dict(id="canary-qwen", name="Canary-Qwen 2.5B", org="NVIDIA", category="asr",
      params_total="2.5B", params_active=None, architecture=None, context=None,
      modality="speech→text", license="CC-BY-4.0", release="2025",
      hf="nvidia/canary-qwen-2.5b", notes="EN accuracy leader (v.r.)", commercial=True),
 dict(id="moonshine", name="Moonshine", org="Useful Sensors", category="asr",
      params_total="~60M", params_active=None, architecture=None, context=None,
      modality="speech→text", license="Apache 2.0", release="2024-11",
      hf="usefulsensors/moonshine-base", notes="On-device low-latency edge", commercial=True),
 dict(id="vosk", name="Vosk", org="Alpha Cephei", category="asr",
      params_total="tiny", params_active=None, architecture=None, context=None,
      modality="speech→text", license="Apache 2.0", release="ongoing",
      github="https://github.com/alphacep/vosk-api", notes="Embedded/offline 20+ langs", commercial=True),
 dict(id="whisperx", name="WhisperX", org="m-bain", category="asr",
      params_total=None, params_active=None, architecture="Whisper+pyannote", context=None,
      modality="speech→text (diarization)", license="BSD-2", release="2023",
      github="https://github.com/m-bain/whisperX", notes="Word timestamps + speaker diarization", commercial=True),
 # ---- Embeddings / rerankers ----
 dict(id="qwen3-embedding-8b", name="Qwen3-Embedding-8B", org="Qwen (Alibaba)", category="embedding",
      params_total="8B", params_active=None, architecture=None, context="8K",
      modality="text→vector (4096d)", license="Apache 2.0", release="2025",
      hf="Qwen/Qwen3-Embedding-8B", notes="MTEB ~70.6; multilingual + code leader", commercial=True),
 dict(id="bge-m3", name="BGE-M3", org="BAAI", category="embedding",
      params_total="568M", params_active=None, architecture=None, context="8K",
      modality="text→vector (1024d, dense+sparse)", license="MIT", release="2024",
      hf="BAAI/bge-m3", ollama="bge-m3", notes="Production multilingual default", commercial=True),
 dict(id="nv-embed-v2", name="NV-Embed-v2", org="NVIDIA", category="embedding",
      params_total="7.85B", params_active=None, architecture=None, context="32K",
      modality="text→vector (4096d)", license="NVIDIA Open Model", release="2025",
      hf="nvidia/NV-Embed-v2", notes="Max EN accuracy (~72 MTEB, v.r.)", commercial=True),
 dict(id="nomic-embed-text", name="nomic-embed-text", org="Nomic", category="embedding",
      params_total="137M", params_active=None, architecture=None, context="8K",
      modality="text→vector (768d)", license="Apache 2.0", release="2024",
      hf="nomic-ai/nomic-embed-text-v1.5", ollama="nomic-embed-text", notes="Laptop pick", commercial=True),
 dict(id="gte-qwen3", name="gte-Qwen3-8B", org="Alibaba", category="embedding",
      params_total="8B", params_active=None, architecture=None, context=None,
      modality="text→vector (4096d)", license="Apache 2.0", release="2025",
      hf="Alibaba-NLP/gte-Qwen3-8B", notes="Long-context retrieval", commercial=True),
 dict(id="mxbai-embed-large", name="mxbai-embed-large", org="Mixedbread", category="embedding",
      params_total="335M", params_active=None, architecture=None, context="512",
      modality="text→vector (1024d)", license="Apache 2.0", release="2024",
      hf="mixedbread-ai/mxbai-embed-large-v1", ollama="mxbai-embed-large", notes="Best sub-500M", commercial=True),
 dict(id="bge-reranker-v2", name="BGE-reranker-v2-m3", org="BAAI", category="reranker",
      params_total="~570M", params_active=None, architecture=None, context="8K",
      modality="text scoring", license="MIT", release="2024",
      hf="BAAI/bge-reranker-v2-m3", ollama="bge-reranker-v2-m3", notes="Production default reranker", commercial=True),
 dict(id="qwen3-reranker", name="Qwen3-Reranker", org="Qwen (Alibaba)", category="reranker",
      params_total=None, params_active=None, architecture=None, context=None,
      modality="text scoring", license="Apache 2.0", release="2025",
      hf="Qwen/Qwen3-Reranker", notes="Multilingual reranking", commercial=True),
 # ---- 3D ----
 dict(id="hunyuan3d-2", name="Hunyuan3D 2.x", org="Tencent", category="model3d",
      params_total=None, params_active=None, architecture="Multi-view diffusion", context=None,
      modality="image→3D mesh+PBR", license="Tencent Hunyuan Community", release="2025-2026",
      hf="Tencent-Hunyuan/Hunyuan3D-2.0", github="https://github.com/Tencent-Hunyuan/Hunyuan3D-2", notes="Best open mesh+texture quality", commercial=True),
 dict(id="trellis-2", name="TRELLIS.2", org="Microsoft", category="model3d",
      params_total="4B", params_active=None, architecture="Structured latent", context=None,
      modality="image→3D (PBR to 4K)", license="MIT", release="2025-12",
      hf="microsoft/TRELLIS.2-4B", github="https://github.com/microsoft/TRELLIS", notes="Cleanest 3D license; GLB/OBJ/PLY", commercial=True),
 dict(id="triposr", name="TripoSR", org="Stability AI + Tripo", category="model3d",
      params_total=None, params_active=None, architecture="Feed-forward reconstruction", context=None,
      modality="image→3D", license="Apache 2.0 (check)", release="2024",
      hf="stabilityai/TripoSR", notes="Sub-second real-time", commercial=True),
 dict(id="stable-fast-3d", name="Stable Fast 3D", org="Stability AI", category="model3d",
      params_total=None, params_active=None, architecture="Feed-forward", context=None,
      modality="image→textured mesh", license="Stability Community", release="2024-08",
      hf="stabilityai/stable-fast-3d", notes="<1s on H100", commercial=True),
 dict(id="sam3d", name="SAM 3D", org="Meta", category="model3d",
      params_total=None, params_active=None, architecture=None, context=None,
      modality="photo→gaussian splat/mesh", license="SAM License", release="2025-11",
      github="https://github.com/facebookresearch/sam3d", notes="Objects + human body from one photo", commercial=True),
 # ---- Important open LLM smalls / fully open ----
 dict(id="smollm3-3b", name="SmolLM3-3B", org="Hugging Face", category="llm",
      params_total="3B", params_active=None, architecture="Dense", context="128K",
      modality="text", license="Apache 2.0", release="2025",
      hf="HuggingFaceTB", notes="Fully open (data+code+weights)", commercial=True),
 dict(id="olmo-2", name="OLMo 2", org="AI2", category="llm",
      params_total="7B-32B", params_active=None, architecture="Dense", context="8K+",
      modality="text", license="Apache 2.0", release="2025",
      hf="allenai", notes="Fully open (data+code+weights)", commercial=True),
 dict(id="pythia", name="Pythia", org="EleutherAI", category="llm",
      params_total="12B", params_active=None, architecture="Dense", context="2K",
      modality="text", license="Apache 2.0", release="2023",
      hf="EleutherAI/pythia-12b", notes="Fully-open research lineage", commercial=True),
 dict(id="falcon-3", name="Falcon 3", org="TII", category="llm",
      params_total="1B-235B", params_active=None, architecture="Dense+Mamba-hybrid", context="32K+",
      modality="text", license="Apache 2.0", release="2024-12",
      hf="tiiuae/Falcon3-235B-Instruct", notes="UAE open family", commercial=True),
 dict(id="granite", name="IBM Granite 3.x", org="IBM", category="llm",
      params_total="1B-34B", params_active=None, architecture="Dense", context="128K",
      modality="text", license="Apache 2.0", release="2024-2025",
      hf="ibm-granite", notes="Enterprise governance", commercial=True),
 dict(id="mixtral-8x7b", name="Mixtral 8x7B", org="Mistral AI", category="llm",
      params_total="47B", params_active="13B", architecture="MoE", context="32K",
      modality="text", license="Apache 2.0", release="2023-12",
      hf="mistralai/Mixtral-8x7B-Instruct-v0.1", ollama="mixtral", notes="The MoE that made sparse famous", commercial=True),
 dict(id="llama-3.3-70b", name="Llama 3.3 70B", org="Meta", category="llm",
      params_total="70B", params_active=None, architecture="Dense", context="128K",
      modality="text", license="Llama 3.3 Community", release="2024-12",
      hf="meta-llama/Llama-3.3-70B-Instruct", ollama="llama3.3:70b", notes="Most-deployed open 70B", commercial=True),
 dict(id="llama-3.1-8b", name="Llama 3.1 8B", org="Meta", category="llm",
      params_total="8B", params_active=None, architecture="Dense", context="128K",
      modality="text", license="Llama 3.1 Community", release="2024-07",
      hf="meta-llama/Llama-3.1-8B-Instruct", ollama="llama3.1:8b", notes="Classic single-GPU default", commercial=True),
 dict(id="deepseek-v4-flash-vision", name="DeepSeek V4-Flash-Vision-Exp", org="DeepSeek", category="vlm",
      params_total="305B", params_active=None, architecture="Multimodal MoE (FP8)", context=None,
      modality="text+image", license="MIT", release="2026-08-31",
      hf="deepseek-ai/DeepSeek-V4-Flash-Vision-Exp", notes="First V4 vision model; experimental", commercial=True),
 dict(id="kimi-k2.7-code", name="Kimi K2.7-Code", org="Moonshot AI", category="llm",
      params_total="1T", params_active="32B", architecture="MoE (compressed-tensors 4-bit pack)", context="256K",
      modality="text+image+video", license="Modified MIT", release="2026-06-12",
      hf="moonshotai/Kimi-K2.7-Code", github="https://github.com/MoonshotAI/Kimi-K2", api="https://platform.moonshot.ai",
      notes="Coding specialist; +21.8% Kimi Code Bench v2, -30% reasoning tokens (v.r.); ~595GB; vLLM/SGLang day-one", commercial=True),
 dict(id="qwen3.5-9b", name="Qwen3.5-9B / 4B", org="Qwen (Alibaba)", category="llm",
      params_total="4B-9B", params_active=None, architecture="Dense", context="256K",
      modality="text+image+video", license="Apache 2.0", release="2026-02-27",
      hf="Qwen/Qwen3.5-9B", github="https://github.com/QwenLM/Qwen3",
      notes="Small multimodal agentic Qwen3.5 sizes", commercial=True),
 dict(id="hunyuan-hy3", name="Hunyuan Hy3", org="Tencent", category="llm",
      params_total="295B", params_active="21B", architecture="MoE", context="256K",
      modality="text", license="Apache 2.0", release="2026-07-06",
      hf=None, github="https://github.com/Tencent-Hunyuan", api=None,
      notes="Open-weight reasoning/agents; reasoning_effort knob; Apache 2.0 (HF org: Tencent-Hunyuan)", commercial=True),
 dict(id="seed-oss-36b", name="Seed-OSS-36B", org="ByteDance Seed", category="reasoning",
      params_total="36B", params_active=None, architecture="Dense", context="32K",
      modality="text", license="Apache 2.0", release="2025-08-20",
      hf="ByteDance-Seed/Seed-OSS-36B-Instruct", github="https://github.com/ByteDance-Seed/Seed-OSS",
      notes="ByteDance rare open-weight release; dense thinking model", commercial=True),
 dict(id="qwen2.5-omni-7b", name="Qwen2.5-Omni-7B", org="Qwen (Alibaba)", category="omni",
      params_total="7B", params_active=None, architecture="Thinker-Talker", context="32K",
      modality="speech+text+image+video", license="Apache 2.0", release="2025-03",
      hf="Qwen/Qwen2.5-Omni-7B", github="https://github.com/QwenLM/Qwen2.5-Omni",
      notes="The open realtime speech-to-speech reference", commercial=True),
 dict(id="glm-4-voice", name="GLM-4-Voice", org="Z.ai (Zhipu)", category="omni",
      params_total="9B", params_active=None, architecture="Flow-matching decoder", context=None,
      modality="speech+text", license="Apache 2.0", release="2025-03",
      hf="zai-org/glm-4-voice-9b", github="https://github.com/zai-org/GLM-4-Voice",
      notes="Streaming speech-to-speech with emotion control", commercial=True),
 dict(id="kimi-audio", name="Kimi-Audio", org="Moonshot AI", category="omni",
      params_total="7B", params_active=None, architecture="Audio LLM", context=None,
      modality="audio understand+generate+converse", license="Code MIT/Apache-2.0 (check weights)", release="2025-02",
      hf="moonshotai", github="https://github.com/MoonshotAI/Kimi-Audio",
      notes="13M+ hours training (v.r.); unified audio foundation model", commercial=True),
 dict(id="step-audio", name="Step-Audio", org="StepFun", category="omni",
      params_total=None, params_active=None, architecture="Speech-to-speech", context=None,
      modality="speech+text", license="Apache 2.0", release="2025-02",
      hf="stepfun-ai/Step-Audio-Chat", github="https://github.com/stepfun-ai/Step-Audio",
      notes="130+ language claims (v.r.)", commercial=True),
 dict(id="minicpm-o-2.6", name="MiniCPM-o 2.6", org="OpenBMB", category="omni",
      params_total="8B", params_active=None, architecture="Omni", context=None,
      modality="speech+text+image+video", license="Apache 2.0 (check)", release="2025-01",
      hf="openbmb", github="https://github.com/OpenBMB/MiniCPM-o",
      notes="Edge omni: audio+vision+text", commercial=True),
 dict(id="olmocr", name="olmOCR", org="Allen Institute for AI", category="ocr",
      params_total="7B", params_active=None, architecture="Qwen2.5-VL based", context=None,
      modality="document image to text", license="Apache 2.0", release="2025-01",
      hf="allenai/olmOCR-7B-0225-preview", github="https://github.com/allenai/olmocr",
      notes="LLM-grade OCR for documents; vLLM-servable", commercial=True),
 dict(id="got-ocr2", name="GOT-OCR2", org="StepFun", category="ocr",
      params_total="580M", params_active=None, architecture="Encoder-decoder", context=None,
      modality="document OCR", license="Apache 2.0", release="2025",
      hf="stepfun-ai", github="https://github.com/Ucas-HaoranWei/GOT-OCR2.0",
      notes="Text, tables, formulas, music notation", commercial=True),
 dict(id="internvl3-8b", name="InternVL3 8B/78B", org="OpenGVLab (Shanghai AI Lab)", category="vlm",
      params_total="8B-78B", params_active=None, architecture="VLM", context="128K",
      modality="text+image+video", license="Apache 2.0 (8B); other (78B - check)", release="2025",
      hf="OpenGVLab/InternVL3-8B", github="https://github.com/OpenGVLab/InternVL",
      notes="OCR + multilingual document VQA; 8B/14B/38B Apache, 78B license:other", commercial=True),
 dict(id="minicpm5-2b", name="MiniCPM5-2B", org="OpenBMB", category="llm",
      params_total="2B", params_active=None, architecture="Dense", context=None,
      modality="text", license="Apache 2.0", release="2026-09-06",
      hf="openbmb/MiniCPM5-2B", github="https://github.com/OpenBMB/MiniCPM",
      notes="Sep 2026; edge-ai text gen, tool calling, long context; GGUF same-day", commercial=True),
]

def csv_safe(v):
    v = "" if v is None else str(v)
    if any(c in v for c in ',"\n'):
        v = '"' + v.replace('"', '""') + '"'
    return v

def main():
    path = os.path.join(R, "data", "models.json")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump({"generated": "2026-09-09", "source": "ModelAtlas README.md §2/§4",
                   "count": len(M), "models": M}, f, indent=2, ensure_ascii=False)
    cols = ["id","name","org","category","params_total","params_active","architecture",
            "context","modality","license","release","ollama","hf","github","api","notes","commercial"]
    out = [",".join(cols)]
    for m in M:
        out.append(",".join(csv_safe(m.get(c)) for c in cols))
    with open(os.path.join(R, "data", "models.csv"), "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")
    print(f"OK: {len(M)} models -> data/models.json + data/models.csv")

if __name__ == "__main__":
    main()
